In [115]:
import numpy as np
import time

def diagonalDominance(array):
    strength = "Strictly Dominant"
    for i in range(len(array)):
        sum = 0
        for j in range(len(array)):
            if (j != i):
                sum += abs(array[i,j])
        if (abs(array[i,i]) < sum):
            return "Not Diagonally Dominant"
        if  (array[i,i] == sum):
            strength = "Weakly Dominant"
    return strength

def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations

def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations

tol = 1e-6
max_iterations = 300000

In [116]:
#a)
A = np.array([
	[0.582745, 0.48	, 0.10	, 0.  	, 0.  	], 
 [0.48	, 1.044129, 0.46	, 0.10	, 0.  	],
 [0.10	, 0.46	, 1.10431 , 0.44	, 0.10	],
 [0.  	, 0.10	, 0.44	, 0.963889, 0.42	],
 [0.  	, 0.  	, 0.10	, 0.42	, 0.522565]], dtype=float)
b = np.array([1.162745, 2.084129, 2.20431 , 1.923889, 1.042565], dtype=float)
x0 = np.zeros_like(A)


print("Part A")
print("\n")

start_time = time.perf_counter()
solution, iterations = jacobi(A, b, x0, tol, max_iterations)
end_time = time.perf_counter()
print(f"Jacobi Solution: {solution}")
print(f"Jacobi Iterations: {iterations}")
print(f"Jacobi Run-time: {(end_time - start_time)*1e3} ms")

print("\n")

start_time = time.perf_counter()
solution, iterations = gauss_seidel(A, b, x0, tol, max_iterations)
end_time = time.perf_counter()
print(f"Gauss Seidel Solution: {solution}")
print(f"Gauss Seidel Iterations: {iterations}")
print(f"Gauss Seidel Run-time: {(end_time - start_time)*1e3} ms")
print("Diagonal Dominance:")
print(diagonalDominance(A))

Part A


Jacobi Solution: [[1.0000001 1.0000001 1.0000001 1.0000001 1.0000001]
 [1.0000001 1.0000001 1.0000001 1.0000001 1.0000001]
 [1.0000001 1.0000001 1.0000001 1.0000001 1.0000001]
 [1.0000001 1.0000001 1.0000001 1.0000001 1.0000001]
 [1.0000001 1.0000001 1.0000001 1.0000001 1.0000001]]
Jacobi Iterations: 3846
Jacobi Run-time: 537.2659098356962 ms


Gauss Seidel Solution: [[0.99999983 0.99999983 0.99999983 0.99999983 0.99999983]
 [1.0000001  1.0000001  1.0000001  1.0000001  1.0000001 ]
 [0.99999998 0.99999998 0.99999998 0.99999998 0.99999998]
 [0.99999999 0.99999999 0.99999999 0.99999999 0.99999999]
 [1.00000001 1.00000001 1.00000001 1.00000001 1.00000001]]
Gauss Seidel Iterations: 22
Gauss Seidel Run-time: 4.02403250336647 ms
Diagonal Dominance:
Strictly Dominant


In [117]:
#b)
A = np.array([[1, 1], [1, 1.0001]])
b = np.array([1, 1])
x0 = np.zeros_like(b, dtype='float')

print("Part B")
print("\n")

start_time = time.perf_counter()
solution, iterations = jacobi(A, b, x0, tol, max_iterations)
end_time = time.perf_counter()
print(f"Jacobi Solution: {solution}")
print(f"Jacobi Iterations: {iterations}")
print(f"Jacobi Run-time: {(end_time - start_time)*1e3} ms")

print("\n")

start_time = time.perf_counter()
solution, iterations = gauss_seidel(A, b, x0, tol, max_iterations)
end_time = time.perf_counter()
print(f"Gauss Seidel Solution: {solution}")
print(f"Gauss Seidel Iterations: {iterations}")
print(f"Gauss Seidel Run-time: {(end_time - start_time)*1e3} ms")
print("Diagonal Dominance:")
print(diagonalDominance(A))

Part B


Jacobi Solution: [0.999999 0.      ]
Jacobi Iterations: 276325
Jacobi Run-time: 8127.48814560473 ms


Gauss Seidel Solution: [1. 0.]
Gauss Seidel Iterations: 1
Gauss Seidel Run-time: 0.1964215189218521 ms
Diagonal Dominance:
Weakly Dominant


In [118]:
#c)
A = np.array([[1, 1], [1, 1.0001]])
b = np.array([1, 1.0001])
x0 = np.zeros_like(b, dtype='float')

print("Part C")
print("\n")

start_time = time.perf_counter()
solution, iterations = jacobi(A, b, x0, tol, max_iterations)
end_time = time.perf_counter()
print(f"Jacobi Solution: {solution}")
print(f"Jacobi Iterations: {iterations}")
print(f"Jacobi Run-time: {(end_time - start_time)*1e3} ms")

print("\n")

start_time = time.perf_counter()
solution, iterations = gauss_seidel(A, b, x0, tol, max_iterations)
end_time = time.perf_counter()
print(f"Gauss Seidel Solution: {solution}")
print(f"Gauss Seidel Iterations: {iterations}")
print(f"Gauss Seidel Run-time: {(end_time - start_time)*1e3} ms")
print("Diagonal Dominance:")
print(diagonalDominance(A))

Part C


Jacobi Solution: [9.9990135e-07 1.0000000e+00]
Jacobi Iterations: 276326
Jacobi Run-time: 6135.071735829115 ms


Gauss Seidel Solution: [0.009999 0.990002]
Gauss Seidel Iterations: 46055
Gauss Seidel Run-time: 834.1154307126999 ms
Diagonal Dominance:
Weakly Dominant
