In [19]:
import numpy as np
from scipy.linalg import lu

def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    elapsed_time = end_time - start_time
    return x, max_iterations

def lu_decomposition(A):
    n = len(A)
    L = np.eye(n) # Initialize L as an identity matrix
    U = np.array(A, dtype=float) # Copy of A to avoid
    # modifying the original matrix
    for i in range(n):
        # Eliminate elements below the pivot (U[i, i])
        for j in range(i+1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
            factor = U[j, i] / U[i, i] # Multiplier for row operation
            L[j, i] = factor # Store multiplier in L
            # Update the rows of U
            for k in range(i, n):
                U[j, k] -= factor * U[i, k]
    return L, U

In [24]:
# Example matrix
A = np.array([[2, 3, 1],
              [4, 7, -1],
              [-2, 1, 2]])
# Perform LU Decomposition
P, L, U = lu(A)

print("Matrix A:\n", A)
print("Permutation Matrix P:\n", P)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)

#relationship: P@A ~~ L@U

print("P@A:\n", P@A)
print("L@U:\n", L@U)

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Permutation Matrix P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Lower Triangular Matrix L:
 [[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.5        -0.11111111  1.        ]]
Upper Triangular Matrix U:
 [[ 4.          7.         -1.        ]
 [ 0.          4.5         1.5       ]
 [ 0.          0.          1.66666667]]
P@A:
 [[-2.  1.  2.]
 [ 2.  3.  1.]
 [ 4.  7. -1.]]
L@U:
 [[ 4.  7. -1.]
 [-2.  1.  2.]
 [ 2.  3.  1.]]
